scanners/boostsecurityio/trivy-sbom/module.yaml
```
COSIGN_EXPERIMENTAL=1 cosign verify aquasec/trivy:0.32.0
docker run --rm -ti aquasec/trivy:0.32.0@sha256:973d0df16189c229757aa8e81d48d112123e832d576acf5c02c4cb753451608a
```
=> trivy-sbom: pin Docker image

scanners/boostsecurityio/brakeman/module.yaml
This forces scan even if ./app is not found
See logs here
https://github.com/boost-entropy-ruby/WhatWeb/actions/runs/3246689816/jobs/5325734062#step:3:34
I've tested by pointing the local CLI towards this branch
I have also opened an equivalent PR in `scanner-testing`
Drive-by: add `require_full_repo`
```
poetry run boost scan repo --offline --path $HOME/sandbox/WhatWeb/ --registry-module boostsecurityio/brakeman
21:14:04 [INFO] boost.app: initializing scanner 1.0.0
21:14:05 [INFO] boost.app: preparing repository
21:14:07 [INFO] boost.app: configuring scanners
21:14:09 [INFO] boost.app: starting scanner for HEAD
21:14:10 [ERROR] boost.app: command 'docker start --attach b83cb8f49867eaba0d063f1...' exited with non-zero exit status: 4
21:14:10 [ERROR] boost.app:   Please supply the path to …
```
=> brakeman - add --force flag

scanners/boostsecurityio/trivy-image/module.yaml
Trivy has an option to hide the CVEs for which there is no known patch
https://aquasecurity.github.io/trivy/v0.32/docs/vulnerability/examples/filter/#hide-unfixed-vulnerabilities
Zaid has suggested we make that the sane default configuration, but still allow for someone to override it (through environment variable)
=> trivy-image : ignored unfixed CVEs by default

scanners/boostsecurityio/brakeman/module.yaml
This updates the Docker image to fix ruleID in the SARIF
Tested here
https://github.com/boost-sandbox/railsgoat/actions/runs/3270411537/jobs/5379003020
=> brakeman: fix SARIF ruleID

scanners/boostsecurityio/gosec/module.yaml
- To keep mapping simple, we still need to strip the rule.name, otherwise the SARIF contains a CWE text and is not one to one
- Update gosec's Docker image to bring upstream bugfix which was producing bad SARIF in some cases.
Tested here https://github.com/boost-sandbox/intentionally-vulnerable-golang-project/blob/master/.github/workflows/boost.yml#L34
On dev `sandbox` account
-----
```
cosign verify --key https://raw.githubusercontent.com/securego/gosec/26f10e0a7ab6e0bfb561af1757e17243edaf93ec/cosign.pub securego/gosec:2.14.0
Verification for index.docker.io/securego/gosec:2.14.0 --
The following checks were performed on each of these signatures:
- The cosign claims were validated
- The signatures were verified against the specified public key …
```
=> gosec - fix rule mapping and update Docker

scanners/boostsecurityio/trivy-image/module.yaml
update the trivy-image processor
resolve a validation error when the trivy vulnerability does not contain a Title
=> update trivy-image processor

scanners/boostsecurityio/bundler-audit/README.md, scanners/boostsecurityio/bundler-audit/module.yaml, scanners/boostsecurityio/bundler-audit/rules.yaml
Add a module to run bundler-audit.
There were no image available on hand and bundler-audit wasn't too great to fit into a module.
- The exit code is hard coded to 1 if there are findings. 
- Bundler's lockfile parser implicitly depends on the presence in the cwd of a file named `Gemfile` to parse `Gemfile.lock`, even if it doesn't use it or if a custom lockfile path is used.
I'll improve forward the way bundler-audit runs when I have a usable Docker image.
=> Add initial bundler-audit module

scanners/boostsecurityio/npm-audit/module.yaml
SCA findings will now be reported as high confidence.
Ignore the branch name, it's actually for npm audit.
=> Update npm-audit post-processor

scanners/boostsecurityio/native-scanner/rules.yaml
Define a new branch protection rule in the default namespace to check if the branch requires a different reviewer than the last pusher.
=> Add new branch protection rule in default namespace

scanners/boostsecurityio/nancy/README.md, scanners/boostsecurityio/nancy/module.yaml, scanners/boostsecurityio/nancy/rules.yaml
Add a module to run Nancy.
If a `Gopkg.lock` file is present, Nancy will run using `nancy sleuth --path Gopkg.lock`.  Otherwise, Nancy expects its input to be the output of `go list` . The module will run `go list`, but can be configured to load the output of this command from a file.
=> Add Nancy module

scanners/boostsecurityio/gosec/rules.yaml
This requires new CWE categories for:
- `cwe-703`
- `cwe-119`
=> Add missing categories to Gosec rules

scanners/boostsecurityio/nancy/module.yaml
Remove usage of `echo` in the nancy module because it evaluates escaped newlines in JSON strings.
=> nancy: remove echo

scanners/boostsecurityio/safety/module.yaml
Update the safety module
- Pip started polluting the output so pipe its stderr to /dev/null to ensure this doesn't happen again.
- Update the post-processor to handle package name with capital letters.
=> safety: update post-processor and silence pip

scanners/boostsecurityio/native-scanner/module.yaml
Update the Native scanner image.
Changes:
- Add detection for GitHub fine-grained access tokens.
- Fix fingerprint issue with the unpinned dependency rule.
=> BST-2745: Update native-scanner

scanners/boostsecurityio/checkov/rules.yaml
- Fix the description on CKV_AWS_40, CKV_GCP_34, CKV_GHA_7
- Trim unnecessary information from the the pretty name of CKV_AWS_250, CKV_AWS_40, CKV_GCP_34, CKV_OPENAPI_7
=> checkov: fix rule descriptions, trim pretty names

scanners/boostsecurityio/brakeman/rules.yaml, scanners/boostsecurityio/bundler-audit/rules.yaml, scanners/boostsecurityio/nancy/rules.yaml, scanners/boostsecurityio/npm-audit/rules.yaml, scanners/boostsecurityio/safety/rules.yaml, scanners/boostsecurityio/snyk-test/rules.yaml, scanners/boostsecurityio/trivy-image/rules.yaml
Also in prod https://github.com/boostsecurityio/scanner-registry/pull/83
---
Aligned all SCA related rules to have the same labels and groups (also one rule in Brakeman matches some CVEs)
Since we will eventually move those to a shared namespace (instead of copy pasting), I put a generic URL for the documentation. And since we had nothing really interesting anyway for the documentation, I'm sending people to the NIST NVD page explaining CVSS mapping to low, medium, high, critical, etc...
=> BST-3182 Align all SCA rules

scanners/boostsecurityio/codeql/rules.yaml, scanners/boostsecurityio/gitleaks/rules.yaml, scanners/boostsecurityio/gosec/rules.yaml, scanners/boostsecurityio/native-scanner/rules.yaml, scanners/boostsecurityio/semgrep/rules.yaml
Also in prod https://github.com/boostsecurityio/scanner-registry/pull/84
---
Normalizing usage of labels:
- for secrets related rules (gitleaks and built-in to native-scanner)
- added missing `boost-baseline` / `boost-hardened` for:
- CodeQL
- GoSec
- semgrep
---
- each aspect has been regrouped by commit, so feel free to filter in the `Files Changed` tab
-  Normalizing `owasp-top-10` , `cwe-top-25` labels is not addressed in this PR
=> BST-3168, BST-3170, BST-3172 - Align and add missing boost-baseline / boost-hardened 

scanners/boostsecurityio/gosec/rules.yaml
There was a typo CWE-118 is not in supported, but CWE-119 is (that's what was there before)
=> Fix wrong CWE label for Gosec

scanners/boostsecurityio/brakeman/module.yaml, scanners/boostsecurityio/brakeman/rules.yaml, scanners/boostsecurityio/bundler-audit/module.yaml, scanners/boostsecurityio/bundler-audit/rules.yaml, scanners/boostsecurityio/checkov/module.yaml, scanners/boostsecurityio/codeql/module.yaml, scanners/boostsecurityio/codeql/rules.yaml, scanners/boostsecurityio/gitleaks/module.yaml, scanners/boostsecurityio/gitleaks/rules.yaml, scanners/boostsecurityio/gosec/module.yaml, scanners/boostsecurityio/gosec/rules.yaml, scanners/boostsecurityio/nancy/module.yaml, scanners/boostsecurityio/nancy/rules.yaml, scanners/boostsecurityio/native-scanner/module.yaml, scanners/boostsecurityio/native-scanner/rules.yaml, scanners/boostsecurityio/npm-audit/module.yaml, scanners/boostsecurityio/npm-audit/rules.yaml, scanners/boostsecurityio/safety/module.yaml, scanners/boostsecurityio/safety/rules.yaml, scanners/boostsecurityio/semgrep/module.yaml, scanners/boostsecurityio/semgrep/rules.yaml, scanners/boostsecurityio/snyk-test/module.yaml, scanners/boostsecurityio/snyk-test/rules.yaml, scanners/boostsecurityio/trivy-image/module.yaml, scanners/boostsecurityio/trivy-sbom-image/module.yaml, scanners/boostsecurityio/trivy-sbom/module.yaml
- Normalize module names
- Force sync of all rules.yaml (with extra whitespace) --- this is a hack until we stop doing differential push which is creating more problems than having advantage for now
- Drive-by fix up CWE-190 -> CWE-119 (error in previous run)
=> Normalize module names and force sync of all rules.yaml

scanners/boostsecurityio/semgrep/rules.yaml
The CWE missing and impacting Coupa:
CWE-328 and CWE-1333.
this adds CWE-328
=> BST-3366 Adds CWE mapping to semgrep.

scanners/boostsecurityio/semgrep/rules.yaml
semgrep rules db is missing support for CWE-1333. The PR adds that rule.
There is a dependency on the rules-management PR https://github.com/boostsecurityio/boostsec-rules-management/pull/41 for the missing label in rules management.
=> BST-3370 Adds CWE-1333 in semgrep rules db.

scanners/boostsecurityio/trivy-image/module.yaml
- https://github.com/boostsecurityio/boostsec-scanner-trivy/commit/d829d1c8c412556222331b0550e26d4d547ee37d `BST-2915 Upgrade poetry, flake8, mypy (#12)`
- https://github.com/boostsecurityio/boostsec-scanner-trivy/commit/63d4980e0aefd170bce19b88cb63be5bf5b11b19 `BST-3207 Aligning severity to the standard SCA mapping (#13)`
- https://github.com/boostsecurityio/boostsec-scanner-trivy/commit/49401ca3fa20744bc9a80af2d462d04c816f2650 `BST-2931 Cruft upgrade: Python 3.10 (#14)`
=> Deploying latest trivy-image main branch on DEV

scanners/boostsecurityio/nancy/module.yaml, scanners/boostsecurityio/npm-audit/module.yaml, scanners/boostsecurityio/safety/module.yaml
- https://github.com/boostsecurityio/boostsec-converter-sca/commit/aa6bcbe3f3fe62839657019f6daa939d38bec3bf `BST-2915 Upgrade poetry, flake8, mypy (#10)`
- https://github.com/boostsecurityio/boostsec-converter-sca/commit/ca8a40dda47f3e5c92b71d6bf14025ab179987e1 `Upgrade to latest base image 1.0.19 (#11)`
- https://github.com/boostsecurityio/boostsec-converter-sca/commit/6e4b6c1a2d1147c0ea49e847608ba8f829caa052 `BST-2931 Cruft upgrade: Python 3.10 (#12)`
- https://github.com/boostsecurityio/boostsec-converter-sca/commit/9016a1889ceab9011a0b4e1f391ce3c8b5da3d1d `nancy: remove ecosystem from package name (#9)`
- https://github.com/boostsecurityio/boostsec-converter-sca/commit/aa6bcbe3f3fe62839657019f6daa939d38bec3bf `BST-2915 Upgrade poetry, flake8, mypy (#10)`
- …
=> Deploying latest safety, nancy, npm-audit main branch on DEV

scanners/boostsecurityio/gitleaks/module.yaml
- https://github.com/boostsecurityio/boostsec-scanner-gitleaks/commit/402d6643822d46c03420097a295c0d0e16a77add `Run cruft upgrade - SBOM Signing (#4)`
- https://github.com/boostsecurityio/boostsec-scanner-gitleaks/commit/4398b4cc38447dd0dd881c81a3dc7b685b8f8c5a `BST-2915 Upgrade poetry, flake8, mypy (#5)`
- https://github.com/boostsecurityio/boostsec-scanner-gitleaks/commit/4e8555e86ecfdcf24630c6bd67484a6753e0353d `Upgrade to latest base image 1.0.19 (#6)`
- https://github.com/boostsecurityio/boostsec-scanner-gitleaks/commit/da8840839b3fb85630a68c118b81cf056307efdb `BST-2931 Cruft upgrade: Python 3.10 (#7)`
=> Deploying latest gitleaks main branch on DEV

scanners/boostsecurityio/trivy-sbom-image/module.yaml
- https://github.com/boostsecurityio/boostsec-scanner-trivy-sbom/commit/75fa5d92ac935d6156b69958e08819eb9ed608fc `BST-2915 Upgrade poetry, flake8, mypy (#3)`
- https://github.com/boostsecurityio/boostsec-scanner-trivy-sbom/commit/8f6f058f31f512dc7510365c0a5dc2d18189ece9 `Upgrade to latest base image 1.0.19 (#4)`
- https://github.com/boostsecurityio/boostsec-scanner-trivy-sbom/commit/2077b09e1bd96c0db3b558a1c6b80a69a2dedc80 `BST-2931 Cruft upgrade: Python 3.10 (#5)`
=> Deploying latest trivy-sbom-image main branch on DEV
