boostsecurityio/scanner-testing

.github/workflows/registry-scanner.yaml, scanners/boostsecurityio/brakeman-scanner/rules.yaml, scanners/boostsecurityio/snyk-scanner/rules.yaml
- image `v1.0.0`
- New input variables `api_token` and `api_endpoint`
=> Update image version and input variables

.github/workflows/registry-scanner.yaml
Same as https://github.com/boostsecurityio/scanner-registry/pull/27
=> [Security] - Only listen to push on main branch, which is protected

.github/workflows/registry-scanner.yaml
DO NOT MERGE - This is pending a deployment
=> Use system API key

scanners/boostsecurityio/semgrep/rules.yaml
Ensure the new api key is working.
Will revert after
=> Change a rules.yaml to test rules upload

scanners/boostsecurityio/semgrep/rules.yaml
Reverts boostsecurityio/scanner-testing#17
=> Revert "Change a rules.yaml to test rules upload"

.github/workflows/registry-scanner.yaml, scanners/boostsecurityio/brakeman/rules.yaml
Reverts https://github.com/boostsecurityio/scanner-testing/pull/26
=> Revert "Debug upload endpoint"

.github/workflows/registry-scanner.yaml
Changes:
- Implemented graphql client to upload rules.
=> Update registry action to v1.0.1

scanners/boostsecurityio/semgrep/module.yaml
Bringing bug fix https://github.com/boostsecurityio/boostsec-scanner-semgrep/pull/7
=> semgrep - update Docker to fix CWE mapping bug

scanners/boostsecurityio/brakeman/rules.yaml
=> brakeman - add missing CWE-295

scanners/boostsecurityio/gosec/module.yaml
Required to find nested modules in a repo
=> Gosec Recursive Command

scanners/boostsecurityio/brakeman/rules.yaml, scanners/boostsecurityio/codeql/rules.yaml, scanners/boostsecurityio/gitleaks/rules.yaml, scanners/boostsecurityio/gosec/rules.yaml, scanners/boostsecurityio/native-scanner/rules.yaml, scanners/boostsecurityio/semgrep/rules.yaml, scanners/boostsecurityio/snyk-test/rules.yaml, scanners/boostsecurityio/trivy-image/rules.yaml
Those are category name/identifier, the pretty name is now defined on the server side.
=> Apply the new curated groups

README.md, scanners/boostsecurityio/codeql/README.md, scanners/boostsecurityio/codeql/module.yaml, scanners/boostsecurityio/gitleaks/README.md, scanners/boostsecurityio/gitleaks/module.yaml
Bring the changes from https://github.com/boostsecurityio/scanner-registry/pull/51 in dev
=> Update CodeQL and GitLeaks

scanners/boostsecurityio/native-scanner/rules.yaml
This comes after refactoring groups, to better align the terminology between groups and categories.
New categories have been pushed to rules management service already.
=> Refactor categories

scanners/boostsecurityio/trivy-sbom-image/module.yaml
Allows ingestion of SBOM created from the content of a container
=> Trivy Image SBOM Scanner

scanners/boostsecurityio/bundler-audit/module.yaml
Changes:
- https://github.com/boostsecurityio/boostsec-scanner-bundler-audit/pull/6
=> Update bundler-audit image

scanners/boostsecurityio/npm-audit/README.md, scanners/boostsecurityio/npm-audit/module.yaml, scanners/boostsecurityio/npm-audit/rules.yaml
=> Add npm audit module

scanners/boostsecurityio/npm-audit/module.yaml
Fix the severity to level mapping in npm-audit.
=> Update npm-audit post-processor

scanners/boostsecurityio/bundler-audit/module.yaml
Fix the severity to level mapping in bundler-audit.
=> Update bundler-audit post-processor

scanners/boostsecurityio/codeql/module.yaml
Update CodeQL post processor image. Fixes: CodeQL messages that included related locations.
=> Update CodeQL processor

scanners/boostsecurityio/trivy-sbom-image/module.yaml
New version of Trivy Image SBOM using post process.
=> Trivy Image SBOM Post Process

scanners/boostsecurityio/bundler-audit/rules.yaml, scanners/boostsecurityio/nancy/rules.yaml, scanners/boostsecurityio/native-scanner/rules.yaml, scanners/boostsecurityio/npm-audit/rules.yaml, scanners/boostsecurityio/safety/rules.yaml, scanners/boostsecurityio/snyk-test/rules.yaml
DO NOT MERGE - Wait for migration to run (adding new category to DB)
=> Normalize all SCA to use same category

scanners/boostsecurityio/brakeman/rules.yaml, scanners/boostsecurityio/checkov/rules.yaml, scanners/boostsecurityio/npm-audit/README.md
Identical to other PR https://github.com/boostsecurityio/scanner-registry/pull/80
=> Add boost-baseline, boost-hardened labels to brakeman

scanners/boostsecurityio/trivy-image/module.yaml
New converter is aligned with other SCA scanners
=> BST-3207 Latest Trivy Converter Version

scanners/boostsecurityio/codeql/module.yaml
- https://github.com/boostsecurityio/boostsec-scanner-codeql/commit/c21db8b09ebaecd9021f2ed08dde47c3b7775d1f `BST-2915 Upgrade poetry, flake8, mypy (#10)`
- https://github.com/boostsecurityio/boostsec-scanner-codeql/commit/fe5c7be122e474ede1c0970308ab3191a5711471 `Upgrade to latest base image 1.0.19 (#11)`
- https://github.com/boostsecurityio/boostsec-scanner-codeql/commit/34c921e9c507f98db39ca8b647498f0235e8e265 `BST-2931 Cruft upgrade: Python 3.10 (#12)`
=> Deploying latest codeql main branch on DEV

scanners/boostsecurityio/checkov/module.yaml
- https://github.com/boostsecurityio/boostsec-scanner-checkov/commit/dc98f3970bec8d42e5c9b2c456828705b1403acf `BST-2931 Cruft upgrade: Python 3.10 (#5)`
=> Deploying latest checkov main branch on DEV

scanners/boostsecurityio/brakeman/module.yaml
- https://github.com/boostsecurityio/boostsec-scanner-brakeman/commit/9c178853cf1d834ea6f6a0feefa234b2ae1d3ca9 `Run cruft upgrade - SBOM Signing (#7)`
- https://github.com/boostsecurityio/boostsec-scanner-brakeman/commit/4078af688b787a80c6c27d4258c1dfa4cc9f4195 `BST-2915 Upgrade poetry, flake8, mypy (#8)`
- https://github.com/boostsecurityio/boostsec-scanner-brakeman/commit/0b71fa28aeaf802c3c85e5fa5cbb84c74f870b2f `BST-2931 Cruft upgrade: Python 3.10 (#10)`
=> Deploying latest brakeman main branch on DEV

.github/workflows/registry-scanner.yaml, scanners/boostsecurityio/bundler-audit/module.yaml, scanners/boostsecurityio/bundler-audit/rules.yaml
- https://github.com/boostsecurityio/boostsec-scanner-bundler-audit/commit/a4fd05299dc04e33a2cd99c6d5b096d725f72804 `BST-2915 Upgrade poetry, flake8, mypy (#9)`
- https://github.com/boostsecurityio/boostsec-scanner-bundler-audit/commit/1ebbdcc70d2cfcb52f01b4fbee6a52158a93ffad `Upgrade to latest base image 1.0.19 (#10)`
- https://github.com/boostsecurityio/boostsec-scanner-bundler-audit/commit/3f3dff50a165b907d0b3193969c6c3148c700d80 `BST-2931 Cruft upgrade: Python 3.10 (#11)`
=> Deploying latest bundler-audit main branch on DEV
